### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by changho3995** [Ashinch/ReadYou#444] opened 2023-07-31 23:23 UTC
**1. Environment**

-   Device: [Samsung GalaxyS23]
-   OS: [Android 13]
-   APP: [0.9.8]

**2. Describe the feature request**

_(I may not respond in a timely manner, but you will be notified when this issue is resolved or refused to be resolved.)

On the flow, it would be nice if the list was sorted from oldest to newest.

**Comment by dontobi** [comment] 2024-01-28 07:44
Duplicate of #120

This issue can therefore be closed.

**Closed** 2024-01-30 18:55 UTC
Labels: duplicate
