### ISSUE TITLE
Swipe to left/right to mark as read should remove read item in unread article list

### ISSUE THREAD

**Issue by TonyRL** [Ashinch/ReadYou#916] opened 2024-12-05 23:36 UTC
**1. Environment**

-   Device: S23+
-   OS: Android 14
-   APP: 0.11.0 - 0.11.1

**2. Describe the bug**

1. Set Swipe right to toggle read in Interaction setting
2. View a feed in unread article list
3. Swipe right articles
4. Selected article should be removed from unread article list

<details>
<summary>Screen record of v0.11.0 and v0.11.1</summary>

https://github.com/user-attachments/assets/555aaeb1-362f-4481-91f9-7f7094ce3279
</details>

**3. Expected behaviour**

<details>
<summary>Screen record of v0.10.1</summary>

https://github.com/user-attachments/assets/8351a104-2c8c-409f-9c3c-f958e2c73070
</details>

Feed used: https://wccftech.com/feed

**Comment by nobkd** [comment] 2024-12-06 01:00
I actually like the new behavior, that the items get greyed out first, because I can undo accidental marking as read.
The next time you open the screen, the articles marked as read are gone from this screen.

**Comment by JunkFood02** [comment] 2024-12-06 02:31
expected behavior

**Closed by JunkFood02** 2024-12-06 02:31 UTC
Labels: bug
