### ISSUE TITLE
Hide the default feed group when empty

### ISSUE THREAD

**Issue by LantashTheTokra** [Ashinch/ReadYou#682] opened 2024-04-04 06:47 UTC
**1. Environment**

-   Device: [Pixel 7]
-   OS: [Android 14]
-   APP: [0.9.14]

In the feeds tab, the heading for the default group appears even if there are no feeds in it. There is no way to hide it.

![Screenshot_20240404-024103](https://github.com/Ashinch/ReadYou/assets/84555704/57d78df8-af31-43b8-ab64-7fa5e311d7ea)

I think that it would look better if the default group would only be shown if there was a feed in it.

**Comment by Go-rom** [comment] 2024-05-16 19:27
Hi,

this ticket is a duplicate of https://github.com/Ashinch/ReadYou/issues/96

**Closed** 2024-06-19 09:12 UTC
Labels: enhancement
