### ISSUE TITLE
app gestures

### ISSUE THREAD

**Issue by nykroy** [Ashinch/ReadYou#303] opened 2023-01-03 17:05 UTC
**2. Describe the feature request**
Gestures on rss list for mark as read or pin a RSS news like feeder.

Congrats forma The apps is beutifull and usefull.

Regards!!

**Comment by Ashinch** [comment] 2023-01-07 08:24
@nvllz I have explained the subsequent development plan in the changelog of version 0.8.3.

**Comment by wrnod** [comment] 2023-01-17 17:22
#321 Closed as duplicate of this.
> For useability it would be great if feeds could be refreshed with a pull-down gesture in the unread tab.

**Comment by stef204** [comment] 2023-01-20 19:14
Ability to mark an item as read with a single swipe (right, left or either) is the one critical feature which is missing.

**Comment by stef204** [comment] 2023-01-22 18:35
Code from [here](https://github.com/FredJul/Flym) might be suitable for this `Mark as Read/Unread" with a single swipe (left or right.)

**Comment by Winson-Huang** [comment] 2024-01-16 08:44
I also think `Mark as Read/Unread` with a single swipe (left or right.) will be a good feature, now it only supports Mark as Read but not "Mark as Unread".
And selecting multiple items to mark as read/unread  will also be a good feature, @Ashinch   I know you are currently working on accounts related features, I just want to know if you will consider to improve the local reading features afterwards?

**Comment by Ashinch** [comment] 2024-01-16 09:11
> I also think `Mark as Read/Unread` with a single swipe (left or right.) will be a good feature, now it only supports Mark as Read but not "Mark as Unread".
> 
> And selecting multiple items to mark as read/unread  will also be a good feature, @Ashinch   I know you are currently working on accounts related features, I just want to know if you will consider to improve the local reading features afterwards?

@Winson-Huang 

Interaction optimization starts after integrating some third-party services.

**Closed** 2024-01-30 19:52 UTC
Labels: enhancement
