### ISSUE TITLE
Save App-Settings to File

### ISSUE THREAD

**Issue by WreckingBANG** [Ashinch/ReadYou#349] opened 2023-02-25 14:32 UTC
**1. Environment**

-   Device: [S22-Ultra]
-   OS: [Android 13]
-   APP: [0.9.7]

**2. Describe the feature request**

It would be handy if you could save the Settings of the App including Design into a file.

**Comment by shuvashish76** [comment] 2024-02-12 04:47
Duplicate of #443
This issue can be closed now.

**Closed** 2024-02-16 17:46 UTC
Labels: enhancement
